# ============================================================
# Alpha Diversity Analysis of Kraken2 Genus-Level Profiles
#
# This script calculates alpha diversity metrics from
# genus-level count data generated by Kraken2.
#
# Metrics include:
#   - Observed richness
#   - Shannon index
#   - Effective Shannon diversity
#   - Pielou's evenness
#   - Gini–Simpson index
#   - Inverse Simpson index
#   - Effective Simpson diversity
#   - Simpson equitability
#   - Chao1 richness estimator
#   - ACE richness estimator
#   - Good's coverage
#
# Input data must consist of raw count tables rather than
# relative abundances.
# ============================================================

setwd("D:/ExperimentalRecords/2025_RPOC_Revision/EnzymeDiversity/06_kraken_unclassified")

# ---- Load required package ----

library(vegan)

# ============================================================
# 1. Import genus-level count matrix
# ============================================================

genus_counts <- read.delim(
  file = "kraken_genus_uncla.txt",
  row.names = 1,
  sep = "\t",
  stringsAsFactors = FALSE,
  check.names = FALSE
)

# Transpose matrix to samples × taxa format

genus_counts <- t(genus_counts)

# Ensure matrix format

genus_counts <- as.matrix(genus_counts)

# Verify that all values are non-negative

stopifnot(all(genus_counts >= 0))

cat(
  "Number of samples:",
  nrow(genus_counts), "\n"
)

cat(
  "Number of genera:",
  ncol(genus_counts), "\n"
)

# ============================================================
# 2. Calculate alpha diversity metrics
# ============================================================

# ---- Observed richness ----

observed_richness <- rowSums(genus_counts > 0)

# ---- Shannon diversity ----

shannon_index <- diversity(
  genus_counts,
  index = "shannon",
  base = exp(1)
)

effective_shannon <- exp(shannon_index)

# ---- Pielou's evenness ----

pielou_evenness <- shannon_index / log(observed_richness)

# ---- Simpson diversity ----

gini_simpson <- diversity(
  genus_counts,
  index = "simpson"
)

classic_simpson <- 1 - gini_simpson

inverse_simpson <- diversity(
  genus_counts,
  index = "invsimpson"
)

effective_simpson <- inverse_simpson

simpson_equitability <- inverse_simpson / observed_richness

# ============================================================
# 3. Richness estimators
# ============================================================

# estimateR() requires integer counts

genus_counts_integer <- round(genus_counts)

richness_estimates <- estimateR(
  genus_counts_integer
)

chao1 <- richness_estimates[2, ]

ace <- richness_estimates[4, ]

# ============================================================
# 4. Good's coverage
# ============================================================

singletons <- rowSums(genus_counts_integer == 1)

total_reads <- rowSums(genus_counts_integer)

goods_coverage <- 1 - (singletons / total_reads)

# ============================================================
# 5. Compile results
# ============================================================

alpha_diversity <- data.frame(
  sample_id = rownames(genus_counts),

  observed_richness = observed_richness,

  shannon_index = shannon_index,

  effective_shannon = effective_shannon,

  pielou_evenness = pielou_evenness,

  gini_simpson = gini_simpson,

  classic_simpson = classic_simpson,

  inverse_simpson = inverse_simpson,

  effective_simpson = effective_simpson,

  simpson_equitability = simpson_equitability,

  chao1 = chao1,

  ace = ace,

  goods_coverage = goods_coverage
)

# ============================================================
# 6. Export results
# ============================================================

write.csv(
  alpha_diversity,
  file = "alpha_diversity_metrics.csv",
  row.names = FALSE
)

cat("\nAnalysis completed successfully.\n")

cat(
  "Alpha diversity metrics saved as:\n",
  "alpha_diversity_metrics.csv\n"
)